# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.temperatue_zone_status import TemperatueZoneStatus  # noqa: F401,E501
from swagger_server.models.temperature_zone import TemperatureZone  # noqa: F401,E501
from swagger_server import util


class TemperatureSummary(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, zones: List[TemperatureZone]=None, zone_status: List[TemperatueZoneStatus]=None):  # noqa: E501
        """TemperatureSummary - a model defined in Swagger

        :param zones: The zones of this TemperatureSummary.  # noqa: E501
        :type zones: List[TemperatureZone]
        :param zone_status: The zone_status of this TemperatureSummary.  # noqa: E501
        :type zone_status: List[TemperatueZoneStatus]
        """
        self.swagger_types = {
            'zones': List[TemperatureZone],
            'zone_status': List[TemperatueZoneStatus]
        }

        self.attribute_map = {
            'zones': 'zones',
            'zone_status': 'zoneStatus'
        }
        self._zones = zones
        self._zone_status = zone_status

    @classmethod
    def from_dict(cls, dikt) -> 'TemperatureSummary':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TemperatureSummary of this TemperatureSummary.  # noqa: E501
        :rtype: TemperatureSummary
        """
        return util.deserialize_model(dikt, cls)

    @property
    def zones(self) -> List[TemperatureZone]:
        """Gets the zones of this TemperatureSummary.


        :return: The zones of this TemperatureSummary.
        :rtype: List[TemperatureZone]
        """
        return self._zones

    @zones.setter
    def zones(self, zones: List[TemperatureZone]):
        """Sets the zones of this TemperatureSummary.


        :param zones: The zones of this TemperatureSummary.
        :type zones: List[TemperatureZone]
        """

        self._zones = zones

    @property
    def zone_status(self) -> List[TemperatueZoneStatus]:
        """Gets the zone_status of this TemperatureSummary.


        :return: The zone_status of this TemperatureSummary.
        :rtype: List[TemperatueZoneStatus]
        """
        return self._zone_status

    @zone_status.setter
    def zone_status(self, zone_status: List[TemperatueZoneStatus]):
        """Sets the zone_status of this TemperatureSummary.


        :param zone_status: The zone_status of this TemperatureSummary.
        :type zone_status: List[TemperatueZoneStatus]
        """

        self._zone_status = zone_status
