# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TemperatueZoneStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, name: str=None, value: float=None, units: str='fahrenheit', timestamp: datetime=None):  # noqa: E501
        """TemperatueZoneStatus - a model defined in Swagger

        :param id: The id of this TemperatueZoneStatus.  # noqa: E501
        :type id: str
        :param name: The name of this TemperatueZoneStatus.  # noqa: E501
        :type name: str
        :param value: The value of this TemperatueZoneStatus.  # noqa: E501
        :type value: float
        :param units: The units of this TemperatueZoneStatus.  # noqa: E501
        :type units: str
        :param timestamp: The timestamp of this TemperatueZoneStatus.  # noqa: E501
        :type timestamp: datetime
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'value': float,
            'units': str,
            'timestamp': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'value': 'value',
            'units': 'units',
            'timestamp': 'timestamp'
        }
        self._id = id
        self._name = name
        self._value = value
        self._units = units
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'TemperatueZoneStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TemperatueZoneStatus of this TemperatueZoneStatus.  # noqa: E501
        :rtype: TemperatueZoneStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this TemperatueZoneStatus.

        the unique identifier for the zone  # noqa: E501

        :return: The id of this TemperatueZoneStatus.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this TemperatueZoneStatus.

        the unique identifier for the zone  # noqa: E501

        :param id: The id of this TemperatueZoneStatus.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this TemperatueZoneStatus.

        the name of the zone  # noqa: E501

        :return: The name of this TemperatueZoneStatus.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this TemperatueZoneStatus.

        the name of the zone  # noqa: E501

        :param name: The name of this TemperatueZoneStatus.
        :type name: str
        """

        self._name = name

    @property
    def value(self) -> float:
        """Gets the value of this TemperatueZoneStatus.

        the temperature in the zone  # noqa: E501

        :return: The value of this TemperatueZoneStatus.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value: float):
        """Sets the value of this TemperatueZoneStatus.

        the temperature in the zone  # noqa: E501

        :param value: The value of this TemperatueZoneStatus.
        :type value: float
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def units(self) -> str:
        """Gets the units of this TemperatueZoneStatus.

        the temperature units  # noqa: E501

        :return: The units of this TemperatueZoneStatus.
        :rtype: str
        """
        return self._units

    @units.setter
    def units(self, units: str):
        """Sets the units of this TemperatueZoneStatus.

        the temperature units  # noqa: E501

        :param units: The units of this TemperatueZoneStatus.
        :type units: str
        """
        allowed_values = ["celsius", "fahrenheit"]  # noqa: E501
        if units not in allowed_values:
            raise ValueError(
                "Invalid value for `units` ({0}), must be one of {1}"
                .format(units, allowed_values)
            )

        self._units = units

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this TemperatueZoneStatus.

        the timestamp when the temperature was measured  # noqa: E501

        :return: The timestamp of this TemperatueZoneStatus.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this TemperatueZoneStatus.

        the timestamp when the temperature was measured  # noqa: E501

        :param timestamp: The timestamp of this TemperatueZoneStatus.
        :type timestamp: datetime
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")  # noqa: E501

        self._timestamp = timestamp
