openapi: 3.0.0
info:
  title: home-iot-api
  description: The API for the EatBacon IOT project
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/HANNESSOFTWARE/imaginAIry/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /devices:
    get:
      tags:
      - Device
      description: returns all registered devices
      operationId: get_devices
      parameters:
      - name: skip
        in: query
        description: number of records to skip
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        description: max number of records to return
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: All the devices
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  format: uri
                  example: http://10.0.0.225:8080
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.device_controller
    post:
      tags:
      - Device
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceRegistrationInfo'
      responses:
        "200":
          description: successfully registered device
      x-openapi-router-controller: swagger_server.controllers.device_controller
  /lighting/dimmers/{deviceId}/{value}:
    post:
      tags:
      - Z-Wave
      operationId: set_dimmer
      parameters:
      - name: deviceId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: value
        in: path
        required: true
        style: simple
        explode: false
        schema:
          maximum: 100
          minimum: 0
          type: integer
          format: int32
      responses:
        "200":
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      x-swagger-router-controller: ZWave
      x-openapi-router-controller: swagger_server.controllers.z_wave_controller
  /lighting/dimmers/{deviceId}/{value}/timer/{timeunit}:
    post:
      tags:
      - Z-Wave
      description: sets a dimmer to a specific value on a timer
      operationId: set_dimmer_timer
      parameters:
      - name: deviceId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: value
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
      - name: timeunit
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
      - name: units
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          enum:
          - seconds
          - minutes
          - milliseconds
          default: milliseconds
      responses:
        "200":
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      x-swagger-router-controller: ZWave
      x-openapi-router-controller: swagger_server.controllers.z_wave_controller
  /lighting/switches/{deviceId}:
    get:
      tags:
      - Z-Wave
      operationId: get_switch_state
      parameters:
      - name: deviceId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceState'
      x-swagger-router-controller: ZWave
      x-openapi-router-controller: swagger_server.controllers.z_wave_controller
  /lighting/switches/{deviceId}/{value}:
    post:
      tags:
      - Z-Wave
      operationId: set_switch
      parameters:
      - name: deviceId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: value
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          enum:
          - "true"
          - "false"
      responses:
        "200":
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      x-swagger-router-controller: ZWave
      x-openapi-router-controller: swagger_server.controllers.z_wave_controller
  /lighting/switches/{deviceId}/{value}/timer/{minutes}:
    post:
      tags:
      - Z-Wave
      description: sets a switch to a specific value on a timer
      operationId: set_switch_timer
      parameters:
      - name: deviceId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: value
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          enum:
          - "true"
          - "false"
      - name: minutes
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      x-swagger-router-controller: ZWave
      x-openapi-router-controller: swagger_server.controllers.z_wave_controller
  /image:
    get:
      tags:
      - Environment
      operationId: image_summary
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemperatureSummary'
      x-swagger-router-controller: Environment
      x-openapi-router-controller: swagger_server.controllers.environment_controller
  /image/:
    post:
      tags:
      - Environment
      description: Generates image from imaginAIry
      operationId: generate_image
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImageInfo'
      responses:
        "200":
          description: imaginAlry image
          content:
            image/png:
              schema:
                type: string
                format: binary
                x-content-type: image/png
      x-swagger-router-controller: Environment
      x-openapi-router-controller: swagger_server.controllers.environment_controller
components:
  schemas:
    LightingZone:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        deviceId:
          type: integer
          format: int32
        deviceType:
          type: string
          enum:
          - dimmer
          - switch
        zone:
          type: string
    TemperatureSummary:
      type: object
      properties:
        zones:
          type: array
          items:
            $ref: '#/components/schemas/TemperatureZone'
        zoneStatus:
          type: array
          items:
            $ref: '#/components/schemas/TemperatueZoneStatus'
      description: ok
      example:
        zoneStatus:
        - name: name
          id: id
          units: fahrenheit
          value: 5.962133916683182377482808078639209270477294921875
          timestamp: 2000-01-23T04:56:07.000+00:00
        - name: name
          id: id
          units: fahrenheit
          value: 5.962133916683182377482808078639209270477294921875
          timestamp: 2000-01-23T04:56:07.000+00:00
        zones:
        - inputPosition: 6
          outputPosition: 1
          zone: zone
          name: name
          id: 0
        - inputPosition: 6
          outputPosition: 1
          zone: zone
          name: name
          id: 0
    TemperatureZone:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: integer
          description: the unique identifier for the zone
          format: int32
        name:
          type: string
        inputPosition:
          type: integer
          format: int32
        outputPosition:
          type: integer
          format: int32
        zone:
          type: string
      description: a single temperature zone
      example:
        inputPosition: 6
        outputPosition: 1
        zone: zone
        name: name
        id: 0
    TemperatueZoneStatus:
      required:
      - id
      - timestamp
      - value
      type: object
      properties:
        id:
          type: string
          description: the unique identifier for the zone
        name:
          type: string
          description: the name of the zone
        value:
          type: number
          description: the temperature in the zone
          format: double
        units:
          type: string
          description: the temperature units
          enum:
          - celsius
          - fahrenheit
          default: fahrenheit
        timestamp:
          type: string
          description: the timestamp when the temperature was measured
          format: date-time
      description: status of a single zone
      example:
        name: name
        id: id
        units: fahrenheit
        value: 5.962133916683182377482808078639209270477294921875
        timestamp: 2000-01-23T04:56:07.000+00:00
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
          example: everything is ok
      example:
        code: 0
        message: everything is ok
    HeaterState:
      type: object
      properties:
        id:
          type: string
        state:
          type: string
    DeviceState:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        lastUpdate:
          type: string
          format: date-time
        level:
          type: integer
          format: int32
      example:
        level: 0
        lastUpdate: 2000-01-23T04:56:07.000+00:00
        name: name
        id: id
    ForecastResponse:
      type: object
      properties:
        city:
          $ref: '#/components/schemas/City'
        values:
          type: array
          items:
            $ref: '#/components/schemas/Forecast'
    Forecast:
      type: object
      properties:
        date:
          type: string
          format: date-time
        pressure:
          type: number
          format: double
        humidity:
          type: integer
          format: int32
        windSpeed:
          type: number
          format: double
        clouds:
          type: integer
          format: int32
        temperature:
          $ref: '#/components/schemas/ForecastTemperature'
        weather:
          $ref: '#/components/schemas/WeatherForecast'
    City:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        lat:
          type: number
          format: double
        lon:
          type: number
          format: double
        country:
          type: string
    ForecastTemperature:
      type: object
      properties:
        low:
          type: number
          format: double
        high:
          type: number
          format: double
        morning:
          type: number
          format: double
        day:
          type: number
          format: double
        evening:
          type: number
          format: double
        night:
          type: number
          format: double
    WeatherForecast:
      type: object
      properties:
        summary:
          type: string
        description:
          type: string
        icon:
          type: string
    DeviceRegistrationInfo:
      type: object
      properties:
        uri:
          type: string
          format: uri
          example: http://10.0.0.220:8080
        id:
          type: string
          format: uuid
          example: 0729a580-2240-11e6-9eb5-0002a5d5c51b
    weightedPrompt:
      type: object
      properties:
        name:
          type: string
          format: string
          example: cat
        weight:
          type: integer
          format: int64
          example: 1
    ImageInfo:
      type: object
      properties:
        prompt:
          type: string
          format: string
          example: a scenic landscape
        negative_prompt:
          type: string
          format: string
          example: None
        prompt_strength:
          type: number
          format: double
          example: 7.5
        init_image:
          type: string
          format: string
          example: None
        init_image_strength:
          type: number
          format: double
          example: 0.3
        mask_prompt:
          type: string
          format: string
          nullable: true
          example: None
        mask_image:
          type: string
          format: string
          nullable: true
          example: None
        mask_mode:
          type: string
          enum:
          - replace
          - keep
        mask_modify_original:
          type: boolean
          example: true
        steps:
          type: integer
          format: int64
          nullable: true
        height:
          type: string
          format: string
          example: None
        width:
          type: string
          format: string
          example: None
        fix_faces:
          type: boolean
          example: false
        fix_faces_fidelity:
          type: number
          format: double
          example: 0.2
        sampler_type:
          type: string
          format: string
          example: k_dpmpp_2m
        conditioning:
          type: string
          format: string
          example: None
        model:
          type: string
          format: string
          example: SD-1.5
        seed:
          type: integer
          format: int64
          nullable: true
        upscale:
          type: boolean
          example: false
        tile_mode:
          type: boolean
          example: true
        weightedPrompt:
          type: array
          items:
            $ref: '#/components/schemas/weightedPrompt'

